version: '3'
services:
  app:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: sk-xxx
      OPENAI_ACCESS_TOKEN: xxx
      # API OPENAI_API_KEY
      OPENAI_API_BASE_URL: xxx
      # API OPENAI_API_KEY
      OPENAI_API_MODEL: xxx
      API_REVERSE_PROXY: xxx
      AUTH_SECRET_KEY: xxx
      MAX_REQUEST_PER_HOUR: 0
      TIMEOUT_MS: 60000
      # Socks
      SOCKS_PROXY_HOST: xxx
      # Socks
      SOCKS_PROXY_PORT: xxx
      # HTTPS_PROXY
      HTTPS_PROXY: http://xxx:7890
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
